version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    env_file:
      - ./.env
    depends_on:
      - backend
    restart: unless-stopped
